/* 
  Sketch generated by the Arduino IoT Cloud Thing "Inventory Control"
  https://create.arduino.cc/cloud/things/4c7d47c5-87a5-4e64-8a18-e761026f0e75 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int iron_stock;
  int stone_stock;
  int wood_stock;
  bool reset_stock;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <WiFiNINA.h>
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;

int status = WL_IDLE_STATUS;
int quantity = 0;
int displayScreen = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  while(ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    delay(500);
  }
  
  delay(500);
  CARRIER_CASE = false;
  carrier.begin();
  carrier.display.setRotation(0);
  
  delay(1500);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  carrier.Buttons.update();
  
  if(carrier.Buttons.onTouchDown(TOUCH1)) {
    displayScreen += 1;
    delay(500);
    if (displayScreen >= 3) {
      displayScreen = 0;
    }
    currentScreen;
  }
  else if(carrier.Buttons.onTouchDown(TOUCH3)) {
    displayScreen -= 1;
    delay(500);
    if (displayScreen <= -1) {
      displayScreen = 2;
    }
    currentScreen;
    Serial.println(displayScreen);
  }
  
  else if (carrier.Buttons.onTouchDown(TOUCH0)) {
    quantity -= 1;
 
    if (quantity <= -10) {
      quantity = -10;
    }
    currentScreen();
  }
 
  else if (carrier.Buttons.onTouchDown(TOUCH4)) {
    quantity += 1;
 
    if (quantity >= 10) {
      quantity = 10;
    }
 
    currentScreen();
  }
 
  // CONFIRM BUTTON
  if (carrier.Buttons.onTouchDown(TOUCH2)) {
    updateStock();
  }
}

void currentScreen() {
  if (displayScreen == 0) {
    carrier.display.fillScreen(ST77XX_BLUE); //blue background
    carrier.display.setTextColor(ST77XX_WHITE); //white text
    carrier.display.setTextSize(3); //medium sized text
    carrier.display.setCursor(75, 70); //sets new position for printing (x and y)
    carrier.display.print("STONE");
    carrier.display.setCursor(115, 120); //sets new position for printing (x and y)
    carrier.display.print(quantity);
 
  } else if (displayScreen == 1) {
    carrier.display.fillScreen(ST77XX_RED); //red background
    carrier.display.setTextColor(ST77XX_WHITE); //white text
    carrier.display.setTextSize(3); //medium sized text
    carrier.display.setCursor(80, 70); //sets new position for printing (x and y)
    carrier.display.print("WOOD");
    carrier.display.setCursor(115, 120); //sets new position for printing (x and y)
    carrier.display.print(quantity);
 
  } else if (displayScreen == 2) {
    carrier.display.fillScreen(ST77XX_BLACK); //black background
    carrier.display.setTextColor(ST77XX_WHITE); //white text
    carrier.display.setTextSize(3); //medium sized text
    carrier.display.setCursor(80, 70); //sets new position for printing (x and y)
    carrier.display.print("IRON");
    carrier.display.setCursor(115, 120); //sets new position for printing (x and y)
    carrier.display.print(quantity);
  }
 
  carrier.display.setTextSize(2);
  carrier.display.setCursor(75, 20); //sets new position for printing (x and y)
  carrier.display.print("CONFIRM");
 
  carrier.display.setCursor(10, 70); //sets new position for printing (x and y)
  carrier.display.print("<");
  carrier.display.setCursor(210, 70); //sets new position for printing (x and y)
  carrier.display.print(">");
 
  carrier.display.setTextSize(4); //medium sized text
  carrier.display.setCursor(30, 170); //sets new position for printing (x and y)
  carrier.display.print("-");
  carrier.display.setCursor(180, 170); //sets new position for printing (x and y)
  carrier.display.println("+");
}

void updateStock() {
  if (displayScreen == 0) {
    stone_stock = stone_stock + quantity;
  }
 
  else if (displayScreen == 1) {
    wood_stock = wood_stock + quantity;
  }
 
  else if (displayScreen == 2) {
    iron_stock = iron_stock + quantity;
  }
 
  carrier.display.fillScreen(ST77XX_MAGENTA);
  carrier.display.setCursor(20, 60);
  carrier.display.setTextColor(ST77XX_WHITE);
  carrier.display.setTextSize(2);
  carrier.display.print("Updating stock");
  delay(500);
  carrier.display.print(".");
  delay(500);
  carrier.display.print(".");
  delay(500);
  carrier.display.print(".");
  delay(500);
  carrier.display.print(".");
 
 
  carrier.display.fillScreen(ST77XX_MAGENTA);
  carrier.display.setCursor(20, 60);
  carrier.display.setTextColor(ST77XX_WHITE);
  carrier.display.setTextSize(2);
  carrier.display.print("Update complete!");
 
  carrier.display.setCursor(40, 110);
  carrier.display.print("Stones: ");
  carrier.display.println(stone_stock);
 
  carrier.display.setCursor(40, 130);
  carrier.display.print("Wood: ");
  carrier.display.println(wood_stock);
 
  carrier.display.setCursor(40, 150);
  carrier.display.print("Iron: ");
  carrier.display.println(iron_stock);
 
  quantity = 0;
 
}

void onResetStockChange() {
  if(reset_stock)
  {
  stone_stock = 0;
  iron_stock = 0;
  wood_stock = 0;
  quantity = 0;
  }
}

/*
  Since IronStock is READ_WRITE variable, onIronStockChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIronStockChange()  {
  // Add your code here to act upon IronStock change
}

/*
  Since StoneStock is READ_WRITE variable, onStoneStockChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStoneStockChange()  {
  // Add your code here to act upon StoneStock change
}

/*
  Since WoodStock is READ_WRITE variable, onWoodStockChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWoodStockChange()  {
  // Add your code here to act upon WoodStock change
}
